### ISSUE TITLE
Null pointer 

### ISSUE THREAD

**Issue by dhvanilp** [kajalv/mouse-driver#1]
## Null pointer
- BUG: unable to handle kernel NULL pointer dereference at 0000000000000044
- This is what i got when i saw the dmesg log.

But I am using ubuntu 16.04, would be a great help if you could fix it.

**Comment by kajalv** [comment]
Thanks for bringing it up. Don't have access to Ubuntu nowadays. If you have a solution feel free to raise a pull request.

**Comment by DhvanilP** [comment]
oh thanks for the response.....found a way out though
